---
- name: Task-1
  hosts: all
  become: yes

  vars:
    env_vars: "{{ lookup('file', '.env') | from_yaml }}"
    domain_name: "{{ env_vars.TARGET_DOMAIN }}"
    dns_ip_addr: "{{ env_vars.DNS_SERVER }}"

  tasks:

  - name: Ping servers
    ping:

  - name: Pkgs installation part 1/2
    apt: 
      name: 
        - iptables 
        - htop 
        - ntpsec
        - curl 
        - wget
        - rsyslog
        - fail2ban
        - auditd
        - net-tools
        - dkms
        - linux-headers-amd64
        - build-essential
      state: latest

  - name: Set local DNS server
    copy:
      dest: /etc/resolv.conf
      content: |
        nameserver {{ dns_ip_addr }}
        search {{ domain_name }}

  - name: ntpsec conf
    template:
      src: ntp.conf
      dest: /etc/ntpsec/ntp.conf

  - name: ntpsec restart
    service: 
      name: ntpsec
      state: restarted

  - name: Set timezone
    timezone:
      name: Europe/Minsk
 
  - name: Create custom rsyslog configuration
    template:
      src: logs.conf
      dest: /etc/rsyslog.d/logs.conf

  - name: Restart rsyslog
    service:
      name: rsyslog
      state: restarted


...
