---
- name: Task-1
  hosts: all
  become: true

  vars:
    env_vars: "{{ lookup('file', '.env') | from_yaml }}"
    domain_name: "{{ env_vars.TARGET_DOMAIN }}"
    dns_ip_addr: "{{ env_vars.DNS_SERVER }}"

  tasks:

    - name: Ping servers
      ping:

    - name: Core pkgs installation
      apt:
        name:
          - iptables
          - htop
          - ntpsec
          - curl
          - wget
          - rsyslog
          - fail2ban
          - auditd
          - net-tools
          - dkms
          - linux-headers-amd64
          - build-essential
          - acl
        state: latest

    - name: Set local DNS server
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver {{ dns_ip_addr }}
          search {{ domain_name }}

    - name: ntpsec conf
      template:
        src: ntp.conf
        dest: /etc/ntpsec/ntp.conf

    - name: ntpsec restart
      service:
        name: ntpsec
        state: restarted

    - name: Set timezone
      timezone:
        name: Europe/Minsk

    - name: Create custom rsyslog configuration
      template:
        src: logs.conf
        dest: /etc/rsyslog.d/logs.conf

    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted

    - name: Zabbix installation
      get_url:
        url: https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian13_all.deb
        dest: /tmp/zabbix-release_7.4.deb

    - name: installation dpkg
      apt:
        deb: /tmp/zabbix-release_7.4.deb
        state: present

    - name: Cache apt
      apt:
        update_cache: yes

    - name: Zabbix pkgs extra
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.4-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - postgresql
          - python3-psycopg2
        state: present

    - name: DB user zabbix
      community.postgresql.postgresql_user:
        name: zabbix
        password: "{{ lookup('password', 'credentials/zabbix_password length=16
          chars=ascii_letters,digits') }}"
        state: present
      become_user: postgres

    - name: Create DB for zabbix
      community.postgresql.postgresql_db:
        name: zabbix
        owner: zabbix
        state: present
      become_user: postgres

    - name: Unpack server.sql.gz в /tmp
      shell: gunzip -c /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz >
        /tmp/server.sql
      args:
        creates: /tmp/server.sql
      become: true

    - name: Check if Zabbix DB is empty
      community.postgresql.postgresql_query:
        db: zabbix
        query: "SELECT to_regclass('public.users');"
      register: zbx_check
      become_user: postgres

    - name: Import default PostgreSQL
      community.postgresql.postgresql_script:
        db: zabbix
        path: /tmp/server.sql
        encoding: UTF-8
      when: zbx_check.query_result[0].to_regclass is none
      become_user: postgres

    - name: DBPassword
      ansible.builtin.replace:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "^#?\\s*DBPassword=.*"
        replace: "DBPassword={{ lookup('password', 'credentials/zabbix_password
          length=16 chars=ascii_letters,digits') }}"

    - name: Enable listen 8080 in Zabbix nginx config
      ansible.builtin.replace:
        path: /etc/zabbix/nginx.conf
        regexp: "^#\\s*listen\\s*8080\\s*;"
        replace: "listen 8080;"

    - name: Set server_name in Zabbix nginx config
      ansible.builtin.replace:
        path: /etc/zabbix/nginx.conf
        regexp: "^(\\s*)#\\s*server_name.*"
        replace: "\\1server_name zbx.com;"

    - name: Restart Zabbix stack services
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - zabbix-server
        - zabbix-agent
        - nginx
        - php8.4-fpm
      become: true

    - name: Enable Zabbix stack services
      service:
        name: "{{ item }}"
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent
        - nginx
        - php8.4-fpm
      become: true
...
