---
- name: Enable listen localhost:8080 in Zabbix nginx config
  replace:
    path: /etc/zabbix/nginx.conf
    regexp: "^#\\s*listen\\s*8080\\s*;"
    replace: "listen 127.0.0.1:8080;"

- name: Set server_name in Zabbix nginx config
  replace:
    path: /etc/zabbix/nginx.conf
    regexp: "^(\\s*)#\\s*server_name.*"
    replace: "\\1server_name zabix.{{ domain_name }};"
